a=int(input("Enter first number: "))
b=int(input("Enter second number: "))
print("Addition of ",a, "and" ,b, "is", (a+b))
print("Subtraction of ",a, "and" ,b, "is", (a-b))
print("multiplication of ",a, "and" ,b, "is", (a*b))
print("Division of ",a, "and" ,b, "is", (a/b))